//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food
{
    using System;
    using System.Collections.Generic;
    
    public partial class focktor
    {
        public int ID { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> price { get; set; }
        public string date_frosh { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
