//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int ID { get; set; }
        public string name_food { get; set; }
        public string price { get; set; }
    }
}
